### ISSUE TITLE
Extracted image paths don't appear to be correct?

### ISSUE THREAD

**Issue by clhenrick** [xdamman/mediumexporter#4]
Attempted using [this example post](https://hi.stamen.com/stamen-aws-lambda-tiler-blog-post-76fc1138a145).

The sample Markdown output from `mediumexporter` for the header image at the top of the post:

```
![Some various map tiles of the [MPG Ranch](http://mpgranch.com/) area, in Montana’s Bitterroot Valley.](https://medium2.global.ssl.fastly.net/max/2560/1*sNRRIAtOi6FLSNRC9HSynw.png)
```

Going to that URL I get this error: "Fastly error: unknown domain. Please check that this domain has been added to a service."

When viewing the image source in dev tools on the post in Medium the actual image path appears to be: 

```
https://cdn-images-1.medium.com/max/1000/1*sNRRIAtOi6FLSNRC9HSynw.png
```

Each of the other image paths in the post are incorrect in the markdown output.

**Comment by xdamman** [comment]
Fixed. Thanks for reporting! (and sorry for the delay!)

**Comment by noelmace** [comment]
@xdamman you should reopen this issue because it's still there when using the programmatic API

```
async function importer(link, dir, name) {
  return mediumexporter.getPost(link, {
    output: path.resolve(dir, name),
    hugo: true,
    frontmatter: true
  });
}
```
with https://cdn-images-1.medium.com/max/800/1*mzCbz0Mxihql1Nyz2yAApQ.png
gives `![Our command process in **top**](1*mzCbz0Mxihql1Nyz2yAApQ.png)` instead of `![Our command process in **top**](./images/1mzCbz0Mxihql1Nyz2yAApQ.png)`
